{application,ilopotion,
             [{applications,[kernel,stdlib,elixir,logger,cowboy,plug,
                             plug_cowboy,jason,httpoison]},
              {description,"ilopotion"},
              {modules,['Elixir.Ilopotion',
                        'Elixir.Ilopotion (LilyDesktop\'s conflicted copy 2021-04-24)',
                        'Elixir.Ilopotion.Router',
                        'Elixir.Ilopotion.Router (LilyDesktop\'s conflicted copy 2021-04-24)',
                        'Elixir.Ilopotion.SocketHandler',
                        'Elixir.Ilopotion.SocketHandler (LilyDesktop\'s conflicted copy 2021-04-24)']},
              {registered,[]},
              {vsn,"0.1.0"},
              {mod,{'Elixir.Ilopotion',[]}}]}.
