site_url: https://lilianaosullivan.github.io/ilo/
site_name: Ilo Secure Communication
repo_name: lilianaosullivan/ilo
repo_url: https://github.com/LilianaOSullivan/ilo
copyright: Copyright &copy; 2020 - 2021 Liliana O'Sullivan
theme:
    name: material
    features:
        - navigation.instant
        - navigation.top

markdown_extensions:
    - toc:
        permalink: true
    - attr_list
    - pymdownx.highlight
    - pymdownx.superfences
    - abbr
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
# nav:
# - Architecture.md
# - Configurability.md
# - Development.md
# - Deployment.md
# - Ilo: 'index.md'
# - Swagger.md

extra:
    generator: false
extra_css:
    - css/termynal.css
extra_javascript:
    - js/termynal.js
